### ISSUE TITLE
Kotlin Exceptions

### ISSUE THREAD

**Issue by dreyinger** [fletchgqc/mediator#2]
This is not really an issue but a question: how would you throw a Kotlin exception with Kotlin parameters?
I am currently struggling with this and am not sure whether this is possible.
Something like this:
```kotlin
"exception": { 
     "type": "myPackage.CustomException", 
     "arguments": [ 
         { 
             "className": "kotlin.String", 
             "value": "custom exception message" 
         } 
     ] 
 }
 ```

I would be thankful for any suggestions, thx.

https://github.com/fletchgqc/mediator/blob/c194fee8263bcf35a2650cf9b62d304959b5d521/experiments/experiment.json#L44-L52

**Comment by fletchgqc** [comment]
Hi @dreyinger, good question, could you please open an issue on the CMSB repo?
